services:
  datagate_database:
    image: postgres:16
    container_name: datagate_database
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - datagate_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    networks:
      - datagate-net
volumes:
  datagate_postgres_data:
networks:
  datagate-net:
    external: true
  