spark.app.name                                  DataGate-Spark
spark.driver.cores                              1
spark.driver.memory                             2g
spark.executor.instances                        2
spark.executor.cores                            4
spark.executor.memory                           7g
spark.serializer                                org.apache.spark.serializer.KryoSerializer
spark.scheduler.mode                            FAIR
spark.scheduler.allocation.file                 /opt/spark/conf/fairscheduler.xml
spark.standalone.submit.waitAppCompletion       true
spark.sql.shuffle.partitions                    32
spark.default.parallelism                       32
spark.sql.extensions                            org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.iceberg                       org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.iceberg.type                  rest
spark.sql.catalog.iceberg.uri                   http://iceberg-rest:8181
# spark.sql.catalog.iceberg.catalog-impl          org.apache.iceberg.rest.RESTCatalog
spark.sql.catalog.iceberg.io-impl               org.apache.iceberg.aws.s3.S3FileIO
spark.sql.catalog.iceberg.warehouse             s3://lakehouse/
spark.sql.catalog.iceberg.write.format.default  parquet
spark.sql.catalog.iceberg.s3.endpoint           http://minio:9000
spark.sql.catalog.iceberg.s3.path-style-access  true
spark.sql.catalog.iceberg.s3.region             us-east-1
spark.sql.catalog.iceberg.s3.access-key-id      admin
spark.sql.catalog.iceberg.s3.secret-access-key  miniopassword
spark.sql.session.timeZone                      Asia/Ho_Chi_Minh
spark.driver.extraJavaOptions                   -Daws.region=us-east-1 -Duser.timezone=Asia/Ho_Chi_Minh --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED
spark.executor.extraJavaOptions                 -Daws.region=us-east-1 -Duser.timezone=Asia/Ho_Chi_Minh --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED