services:
  dbt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbt
    volumes:
      - ./dbt_projects:/usr/app
      - ./dbt_profiles:/root/.dbt
    working_dir: /usr/app
    env_file:
      - .env
    command: ["bash", "-lc", "sleep infinity"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "dbt --version >/dev/null 2>&1 || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    ports:
      - "18080:8080"
    networks:
      - datagate-net

networks:
  datagate-net:
    external: true