"""add_is_active_to_tables

Revision ID: 068191752cbe
Revises: e0f1a2b3c4d5
Create Date: 2026-05-18 17:02:49.401034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '068191752cbe'
down_revision: Union[str, Sequence[str], None] = 'e0f1a2b3c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'anomaly_configs', ['table_id'])
    op.alter_column('rules', 'column_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_rules__table_source_status'), table_name='rules')
    op.drop_index(op.f('ix_rules__table_status'), table_name='rules')
    op.create_index('ix_rules__table_active', 'rules', ['table_id', 'is_active'], unique=False)
    op.drop_column('rules', 'rule_description')
    op.add_column('tables', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text("true")))
    op.create_index('ix_tables__is_active', 'tables', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tables__is_active', table_name='tables')
    op.drop_column('tables', 'is_active')
    op.add_column('rules', sa.Column('rule_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index('ix_rules__table_active', table_name='rules')
    op.create_index(op.f('ix_rules__table_status'), 'rules', ['table_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_rules__table_source_status'), 'rules', ['table_id', 'source', 'is_active'], unique=False)
    op.alter_column('rules', 'column_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'anomaly_configs', type_='unique')
    # ### end Alembic commands ###
