"""update anomaly job config

Revision ID: 14936f8a5914
Revises: 6a04da844702
Create Date: 2026-05-14 13:17:47.265662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14936f8a5914'
down_revision: Union[str, Sequence[str], None] = '6a04da844702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lightgbm_anomaly_configs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('batch_time_col', sa.String(length=255), nullable=False),
    sa.Column('required_history_days', sa.Integer(), nullable=False),
    sa.Column('previous_batch_hours', sa.Integer(), nullable=False),
    sa.Column('history_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_sample_per_group', sa.Integer(), nullable=False),
    sa.Column('test_size', sa.Float(), nullable=False),
    sa.Column('random_state', sa.Integer(), nullable=False),
    sa.Column('p_value_alpha', sa.Float(), nullable=False),
    sa.Column('min_history_auc_points', sa.Integer(), nullable=False),
    sa.Column('exclude_cols', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('categorical_cols', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('numeric_cols', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('last_modified_by', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lgbm_anomaly_configs__table_id', 'lightgbm_anomaly_configs', ['table_id'], unique=True)
    op.add_column('lightgbm_auc', sa.Column('feature_config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lightgbm_auc', 'feature_config_snapshot')
    op.drop_index('ix_lgbm_anomaly_configs__table_id', table_name='lightgbm_anomaly_configs')
    op.drop_table('lightgbm_anomaly_configs')
    # ### end Alembic commands ###
