"""remove num_iterations_used

Revision ID: 2d932c93f32b
Revises: 95e6f7a8b9c0
Create Date: 2026-05-19 18:14:36.373282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d932c93f32b'
down_revision: Union[str, Sequence[str], None] = '95e6f7a8b9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anomaly_results', 'num_iterations_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anomaly_results', sa.Column('num_iterations_used', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
