"""baseline schema v1

Revision ID: 33b1385d299a
Revises:
Create Date: 2026-05-22 02:01:09.602247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '33b1385d299a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_roles__name', 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users__email', 'users', ['email'], unique=True)
    op.create_index('ix_users__role_id', 'users', ['role_id'], unique=False)
    op.create_index('ix_users__username', 'users', ['username'], unique=True)
    op.create_table('connections',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('connection_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('query_engine_host', sa.String(length=255), nullable=False),
    sa.Column('query_engine_port', sa.Integer(), nullable=False),
    sa.Column('query_engine_user', sa.String(length=255), nullable=False),
    sa.Column('query_engine_password', sa.Text(), nullable=True),
    sa.Column('rest_url', sa.String(length=255), nullable=False),
    sa.Column('catalog_name', sa.String(length=255), nullable=False),
    sa.Column('catalog_warehouse', sa.String(length=255), nullable=False),
    sa.Column('storage_endpoint_url', sa.String(length=255), nullable=False),
    sa.Column('storage_access_key', sa.String(length=255), nullable=False),
    sa.Column('storage_secret_key', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('last_modified_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_connections__connection_name', 'connections', ['connection_name'], unique=True)
    op.create_index('ix_connections__created_by', 'connections', ['created_by'], unique=False)
    op.create_index('ix_connections__is_active', 'connections', ['is_active'], unique=False)
    op.create_table('tables',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('connection_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('catalog_name', sa.String(length=255), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tables__connection_catalog_schema_table', 'tables', ['connection_id', 'catalog_name', 'schema_name', 'table_name'], unique=True)
    op.create_index('ix_tables__connection_id', 'tables', ['connection_id'], unique=False)
    op.create_index('ix_tables__is_active', 'tables', ['is_active'], unique=False)
    op.create_table('batch_table_metadata',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('batch_added_rows', sa.BigInteger(), nullable=True),
    sa.Column('batch_added_files', sa.Integer(), nullable=True),
    sa.Column('batch_added_files_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('table_total_rows', sa.BigInteger(), nullable=True),
    sa.Column('table_total_files', sa.Integer(), nullable=True),
    sa.Column('table_total_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('processing_date_hour', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_batch_table_metadata__processing_date_hour', 'batch_table_metadata', ['processing_date_hour'], unique=False)
    op.create_index('ix_batch_table_metadata__table_hour', 'batch_table_metadata', ['table_id', 'processing_date_hour'], unique=True)
    op.create_table('batch_table_profiling',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=100), nullable=True),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('standard_deviation', sa.Float(), nullable=True),
    sa.Column('minimum', sa.Float(), nullable=True),
    sa.Column('maximum', sa.Float(), nullable=True),
    sa.Column('min_length', sa.Integer(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('distinctness', sa.Float(), nullable=True),
    sa.Column('approx_count_distinct', sa.BigInteger(), nullable=True),
    sa.Column('processing_date_hour', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_batch_table_profiling__processing_date_hour', 'batch_table_profiling', ['processing_date_hour'], unique=False)
    op.create_index('ix_batch_table_profiling__table_column_hour', 'batch_table_profiling', ['table_id', 'column_name', 'processing_date_hour'], unique=False)
    op.create_index('ix_batch_table_profiling__table_hour_column', 'batch_table_profiling', ['table_id', 'processing_date_hour', 'column_name'], unique=True)
    op.create_table('model_configs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('batch_time_col', sa.String(length=255), nullable=False),
    sa.Column('required_history_days', sa.Integer(), nullable=False),
    sa.Column('previous_batch_hours', sa.Integer(), nullable=False),
    sa.Column('history_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_sample_per_group', sa.Integer(), nullable=False),
    sa.Column('test_size', sa.Float(), nullable=False),
    sa.Column('random_state', sa.Integer(), nullable=False),
    sa.Column('exclude_cols', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('categorical_cols', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('numeric_cols', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('last_modified_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_configs__table_id', 'model_configs', ['table_id'], unique=True)
    op.create_table('model_parameters',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('learning_rate', sa.Float(), nullable=False),
    sa.Column('num_leaves', sa.Integer(), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('min_data_in_leaf', sa.Integer(), nullable=False),
    sa.Column('bagging_fraction', sa.Float(), nullable=False),
    sa.Column('bagging_freq', sa.Integer(), nullable=False),
    sa.Column('feature_fraction', sa.Float(), nullable=False),
    sa.Column('lambda_l1', sa.Float(), nullable=False),
    sa.Column('lambda_l2', sa.Float(), nullable=False),
    sa.Column('min_gain_to_split', sa.Float(), nullable=False),
    sa.Column('max_bin', sa.Integer(), nullable=False),
    sa.Column('num_iterations', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('last_modified_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_parameters__table_id', 'model_parameters', ['table_id'], unique=True)
    op.create_table('quality_thresholds',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('check_type', sa.String(length=50), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=True),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('min_threshold', sa.Float(), nullable=True),
    sa.Column('max_threshold', sa.Float(), nullable=True),
    sa.Column('severity_level', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('last_modified_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quality_thresholds__table_active', 'quality_thresholds', ['table_id', 'is_active'], unique=False)
    op.create_index('ix_quality_thresholds__table_type_column_metric', 'quality_thresholds', ['table_id', 'check_type', 'column_name', 'metric_name'], unique=True)
    op.create_table('rules',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('severity_level', sa.String(length=50), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=True),
    sa.Column('constraint_name', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_value', sa.String(length=255), nullable=True),
    sa.Column('suggesting_rule', sa.String(length=255), nullable=True),
    sa.Column('code_for_constraint', sa.String(length=512), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('last_modified_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rules__table_active', 'rules', ['table_id', 'is_active'], unique=False)
    op.create_index('ix_rules__table_column', 'rules', ['table_id', 'column_name'], unique=False)
    op.create_index('ix_rules__table_severity', 'rules', ['table_id', 'severity_level'], unique=False)
    op.create_index('ix_rules__table_source_column_code', 'rules', ['table_id', 'source', 'column_name', 'code_for_constraint'], unique=True)
    op.create_table('anomaly_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('model_parameter_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('processing_date_hour', sa.DateTime(), nullable=False),
    sa.Column('auc_score', sa.Float(), nullable=True),
    sa.Column('parameter_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shap_top_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_parameter_id'], ['model_parameters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anomaly_results__param_hour', 'anomaly_results', ['model_parameter_id', 'processing_date_hour'], unique=False)
    op.create_index('ix_anomaly_results__table_hour', 'anomaly_results', ['table_id', 'processing_date_hour'], unique=True)
    op.create_table('quality_check_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('check_type', sa.String(length=50), nullable=False),
    sa.Column('threshold_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('rule_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('anomaly_result_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('column_name', sa.String(length=255), nullable=True),
    sa.Column('metric_name', sa.String(length=255), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('min_threshold', sa.Float(), nullable=True),
    sa.Column('max_threshold', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('severity_level', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_date_hour', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_result_id'], ['anomaly_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threshold_id'], ['quality_thresholds.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quality_check_results__is_resolved', 'quality_check_results', ['is_resolved'], unique=False)
    op.create_index('ix_quality_check_results__status_severity_hour', 'quality_check_results', ['status', 'severity_level', 'processing_date_hour'], unique=False)
    op.create_index('ix_quality_check_results__table_hour', 'quality_check_results', ['table_id', 'processing_date_hour'], unique=False)
    op.create_index('ix_quality_check_results__table_type_hour', 'quality_check_results', ['table_id', 'check_type', 'processing_date_hour'], unique=False)
    op.create_index('uq_quality_check_results__rule_hour', 'quality_check_results', ['table_id', 'check_type', 'rule_id', 'processing_date_hour'], unique=True, postgresql_where='rule_id IS NOT NULL')
    op.create_index('uq_quality_check_results__threshold_hour', 'quality_check_results', ['table_id', 'check_type', 'threshold_id', 'processing_date_hour'], unique=True, postgresql_where='threshold_id IS NOT NULL')
    op.create_table('shap_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('anomaly_result_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('feature_name', sa.String(length=255), nullable=False),
    sa.Column('shap_score', sa.Float(), nullable=False),
    sa.Column('shap_rank', sa.Integer(), nullable=False),
    sa.Column('processing_date_hour', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_result_id'], ['anomaly_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shap_results__result_feature', 'shap_results', ['anomaly_result_id', 'feature_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shap_results__result_feature', table_name='shap_results')
    op.drop_table('shap_results')
    op.drop_index('uq_quality_check_results__threshold_hour', table_name='quality_check_results', postgresql_where='threshold_id IS NOT NULL')
    op.drop_index('uq_quality_check_results__rule_hour', table_name='quality_check_results', postgresql_where='rule_id IS NOT NULL')
    op.drop_index('ix_quality_check_results__table_type_hour', table_name='quality_check_results')
    op.drop_index('ix_quality_check_results__table_hour', table_name='quality_check_results')
    op.drop_index('ix_quality_check_results__status_severity_hour', table_name='quality_check_results')
    op.drop_index('ix_quality_check_results__is_resolved', table_name='quality_check_results')
    op.drop_table('quality_check_results')
    op.drop_index('ix_anomaly_results__table_hour', table_name='anomaly_results')
    op.drop_index('ix_anomaly_results__param_hour', table_name='anomaly_results')
    op.drop_table('anomaly_results')
    op.drop_index('ix_rules__table_source_column_code', table_name='rules')
    op.drop_index('ix_rules__table_severity', table_name='rules')
    op.drop_index('ix_rules__table_column', table_name='rules')
    op.drop_index('ix_rules__table_active', table_name='rules')
    op.drop_table('rules')
    op.drop_index('ix_quality_thresholds__table_type_column_metric', table_name='quality_thresholds')
    op.drop_index('ix_quality_thresholds__table_active', table_name='quality_thresholds')
    op.drop_table('quality_thresholds')
    op.drop_index('ix_model_parameters__table_id', table_name='model_parameters')
    op.drop_table('model_parameters')
    op.drop_index('ix_model_configs__table_id', table_name='model_configs')
    op.drop_table('model_configs')
    op.drop_index('ix_batch_table_profiling__table_hour_column', table_name='batch_table_profiling')
    op.drop_index('ix_batch_table_profiling__table_column_hour', table_name='batch_table_profiling')
    op.drop_index('ix_batch_table_profiling__processing_date_hour', table_name='batch_table_profiling')
    op.drop_table('batch_table_profiling')
    op.drop_index('ix_batch_table_metadata__table_hour', table_name='batch_table_metadata')
    op.drop_index('ix_batch_table_metadata__processing_date_hour', table_name='batch_table_metadata')
    op.drop_table('batch_table_metadata')
    op.drop_index('ix_tables__is_active', table_name='tables')
    op.drop_index('ix_tables__connection_id', table_name='tables')
    op.drop_index('ix_tables__connection_catalog_schema_table', table_name='tables')
    op.drop_table('tables')
    op.drop_index('ix_connections__is_active', table_name='connections')
    op.drop_index('ix_connections__created_by', table_name='connections')
    op.drop_index('ix_connections__connection_name', table_name='connections')
    op.drop_table('connections')
    op.drop_index('ix_users__username', table_name='users')
    op.drop_index('ix_users__role_id', table_name='users')
    op.drop_index('ix_users__email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_roles__name', table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
