"""update anomaly job config v2

Revision ID: 40d114636f41
Revises: 14936f8a5914
Create Date: 2026-05-14 13:21:25.356074

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '40d114636f41'
down_revision: Union[str, Sequence[str], None] = '14936f8a5914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
