"""convert_enums_to_varchar

Revision ID: 477b2bcfc34d
Revises: 068191752cbe
Create Date: 2026-05-18 17:17:00.839215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '477b2bcfc34d'
down_revision: Union[str, Sequence[str], None] = '068191752cbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quality_check_results', 'check_type',
               existing_type=postgresql.ENUM('metadata_threshold', 'profiling_threshold', 'rule', 'anomaly_auc', name='check_type'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('quality_check_results', 'status',
               existing_type=postgresql.ENUM('pass', 'fail', 'error', name='check_status'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('quality_check_results', 'severity_level',
               existing_type=postgresql.ENUM('warning', 'critical', name='severity_level'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('quality_metric_observations', 'metric_scope',
               existing_type=postgresql.ENUM('metadata', 'profiling', 'anomaly', name='metric_scope'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('quality_thresholds', 'metric_scope',
               existing_type=postgresql.ENUM('metadata', 'profiling', 'anomaly', name='metric_scope'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('quality_thresholds', 'severity_level',
               existing_type=postgresql.ENUM('warning', 'critical', name='severity_level'),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'warning'::severity_level"))
    op.alter_column('rules', 'source',
               existing_type=postgresql.ENUM('system', 'manual', name='rule_source'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('rules', 'severity_level',
               existing_type=postgresql.ENUM('warning', 'critical', name='manual_threshold_severity_level'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rules', 'severity_level',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('warning', 'critical', name='manual_threshold_severity_level'),
               existing_nullable=False)
    op.alter_column('rules', 'source',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('system', 'manual', name='rule_source'),
               existing_nullable=False)
    op.alter_column('quality_thresholds', 'severity_level',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('warning', 'critical', name='severity_level'),
               existing_nullable=False,
               existing_server_default=sa.text("'warning'::severity_level"))
    op.alter_column('quality_thresholds', 'metric_scope',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('metadata', 'profiling', 'anomaly', name='metric_scope'),
               existing_nullable=False)
    op.alter_column('quality_metric_observations', 'metric_scope',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('metadata', 'profiling', 'anomaly', name='metric_scope'),
               existing_nullable=False)
    op.alter_column('quality_check_results', 'severity_level',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('warning', 'critical', name='severity_level'),
               existing_nullable=True)
    op.alter_column('quality_check_results', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('pass', 'fail', 'error', name='check_status'),
               existing_nullable=False)
    op.alter_column('quality_check_results', 'check_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('metadata_threshold', 'profiling_threshold', 'rule', 'anomaly_auc', name='check_type'),
               existing_nullable=False)
    # ### end Alembic commands ###
