"""Make model_parameter_id nullable

Revision ID: 55fc705ea607
Revises: ce3593e088e1
Create Date: 2026-05-25 05:00:47.450907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55fc705ea607'
down_revision: Union[str, Sequence[str], None] = 'ce3593e088e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anomaly_results', 'model_parameter_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('anomaly_results_model_parameter_id_fkey'), 'anomaly_results', type_='foreignkey')
    op.create_foreign_key(None, 'anomaly_results', 'model_parameters', ['model_parameter_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'anomaly_results', type_='foreignkey')
    op.create_foreign_key(op.f('anomaly_results_model_parameter_id_fkey'), 'anomaly_results', 'model_parameters', ['model_parameter_id'], ['id'], ondelete='CASCADE')
    op.alter_column('anomaly_results', 'model_parameter_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
