"""update new name

Revision ID: 5e32bfd18e64
Revises: 8f0b8e2a4c1d
Create Date: 2026-05-17 16:04:40.683053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e32bfd18e64'
down_revision: Union[str, Sequence[str], None] = '8f0b8e2a4c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('TRUNCATE TABLE shap_results CASCADE')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_configs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('batch_time_col', sa.String(length=255), nullable=False),
    sa.Column('required_history_days', sa.Integer(), nullable=False),
    sa.Column('previous_batch_hours', sa.Integer(), nullable=False),
    sa.Column('history_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_sample_per_group', sa.Integer(), nullable=False),
    sa.Column('test_size', sa.Float(), nullable=False),
    sa.Column('random_state', sa.Integer(), nullable=False),
    sa.Column('p_value_alpha', sa.Float(), nullable=False),
    sa.Column('min_history_auc_points', sa.Integer(), nullable=False),
    sa.Column('exclude_cols', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('categorical_cols', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('numeric_cols', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('last_modified_by', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_configs__table_id', 'model_configs', ['table_id'], unique=True)
    op.create_table('model_parameters',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('learning_rate', sa.Float(), nullable=False),
    sa.Column('num_leaves', sa.Integer(), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('min_data_in_leaf', sa.Integer(), nullable=False),
    sa.Column('bagging_fraction', sa.Float(), nullable=False),
    sa.Column('bagging_freq', sa.Integer(), nullable=False),
    sa.Column('feature_fraction', sa.Float(), nullable=False),
    sa.Column('lambda_l1', sa.Float(), nullable=False),
    sa.Column('lambda_l2', sa.Float(), nullable=False),
    sa.Column('min_gain_to_split', sa.Float(), nullable=False),
    sa.Column('max_bin', sa.Integer(), nullable=False),
    sa.Column('num_iterations', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('last_modified_by', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_parameters__table_id', 'model_parameters', ['table_id'], unique=True)
    op.create_table('auc_manual_thresholds',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('model_parameter_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('auc_threshold', sa.Float(), nullable=False),
    sa.Column('severity_level', postgresql.ENUM('warning', 'critical', name='manual_threshold_severity_level', create_type=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('last_modified_by', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_parameter_id'], ['model_parameters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auc_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('model_parameter_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('processing_date_hour', sa.DateTime(), nullable=False),
    sa.Column('auc_score', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('parameter_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feature_config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_parameter_id'], ['model_parameters.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auc_results__param_hour', 'auc_results', ['model_parameter_id', 'processing_date_hour'], unique=False)
    op.create_index('ix_auc_results__table_hour', 'auc_results', ['table_id', 'processing_date_hour'], unique=False)
    op.create_table('auc_verify',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('auc_result_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('manual_threshold_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('status', sa.Enum('pass', 'fail', name='model_verify_status'), nullable=False),
    sa.Column('auc_score', sa.Float(), nullable=True),
    sa.Column('auc_threshold', sa.Float(), nullable=True),
    sa.Column('severity_level', postgresql.ENUM('warning', 'critical', name='manual_threshold_severity_level', create_type=False), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('processing_date_hour', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auc_result_id'], ['auc_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manual_threshold_id'], ['auc_manual_thresholds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auc_verify__auc_result_id', 'auc_verify', ['auc_result_id'], unique=True)
    op.create_index('ix_auc_verify__status', 'auc_verify', ['status'], unique=False)
    op.drop_constraint(op.f('shap_results_lightgbm_result_id_fkey'), 'shap_results', type_='foreignkey')
    op.drop_index(op.f('ix_shap_results__result_feature'), table_name='shap_results')
    op.drop_index(op.f('ix_lgbm_verify__result_id'), table_name='lightgbm_auc_verify')
    op.drop_index(op.f('ix_lgbm_verify__status'), table_name='lightgbm_auc_verify')
    op.drop_table('lightgbm_auc_verify')
    op.drop_table('lightgbm_auc_manual_thresholds')
    op.drop_index(op.f('ix_lgbm_results__param_hour'), table_name='lightgbm_auc')
    op.drop_index(op.f('ix_lgbm_results__table_hour'), table_name='lightgbm_auc')
    op.drop_index(op.f('ix_lgbm_results__table_hour_unique'), table_name='lightgbm_auc')
    op.drop_table('lightgbm_auc')
    op.drop_index(op.f('ix_lgbm_params__table_id'), table_name='lightgbm_parameters')
    op.drop_table('lightgbm_parameters')
    op.drop_index(op.f('ix_lgbm_anomaly_configs__table_id'), table_name='lightgbm_anomaly_configs')
    op.drop_table('lightgbm_anomaly_configs')
    op.drop_index(op.f('ix_batch_table_metadata__table_hour'), table_name='batch_table_metadata')
    op.drop_index(op.f('ix_batch_table_metadata_manual_thresholds__table_metric'), table_name='batch_table_metadata_manual_thresholds')
    op.drop_index(op.f('ix_batch_table_metadata_metrics_verify__threshold_batch_unique'), table_name='batch_table_metadata_metrics_verify')
    op.drop_index(op.f('ix_batch_table_profiling__table_hour_column'), table_name='batch_table_profiling')
    op.drop_index(op.f('ix_batch_table_profiling_manual_thresholds__table_column_metric'), table_name='batch_table_profiling_manual_thresholds')
    op.drop_index(op.f('ix_batch_table_profiling_metrics_verify__threshold_batch_unique'), table_name='batch_table_profiling_metrics_verify')
    op.drop_index(op.f('ix_connections__connection_name'), table_name='connections')
    op.drop_index(op.f('ix_permissions__code'), table_name='permissions')
    op.drop_index(op.f('ix_roles__name'), table_name='roles')
    op.drop_index(op.f('ix_rule_verify__rule_hour_unique'), table_name='rule_verify')
    op.add_column('shap_results', sa.Column('auc_result_id', sa.UUID(as_uuid=False), nullable=False))
    op.create_index('ix_shap_results__auc_result_rank', 'shap_results', ['auc_result_id', 'shap_rank'], unique=False)
    op.create_index('ix_shap_results__result_feature', 'shap_results', ['auc_result_id', 'feature_name'], unique=True)
    op.create_foreign_key(None, 'shap_results', 'auc_results', ['auc_result_id'], ['id'], ondelete='CASCADE')
    op.drop_column('shap_results', 'lightgbm_result_id')
    op.drop_index(op.f('ix_tables__connection_catalog_schema_table'), table_name='tables')
    op.drop_index(op.f('ix_tables__connection_id'), table_name='tables')
    op.drop_index(op.f('ix_users__email'), table_name='users')
    op.drop_index(op.f('ix_users__username'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users__username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users__email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_tables__connection_id'), 'tables', ['connection_id'], unique=False)
    op.create_index(op.f('ix_tables__connection_catalog_schema_table'), 'tables', ['connection_id', 'catalog_name', 'schema_name', 'table_name'], unique=True)
    op.add_column('shap_results', sa.Column('lightgbm_result_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shap_results', type_='foreignkey')
    op.create_foreign_key(op.f('shap_results_lightgbm_result_id_fkey'), 'shap_results', 'lightgbm_auc', ['lightgbm_result_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_shap_results__auc_result_rank', table_name='shap_results')
    op.drop_index('ix_shap_results__result_feature', table_name='shap_results')
    op.create_index(op.f('ix_shap_results__result_feature'), 'shap_results', ['lightgbm_result_id', 'feature_name'], unique=True)
    op.drop_column('shap_results', 'auc_result_id')
    op.create_index(op.f('ix_rule_verify__rule_hour_unique'), 'rule_verify', ['rule_id', 'processing_date_hour'], unique=True)
    op.create_index(op.f('ix_roles__name'), 'roles', ['name'], unique=True)
    op.create_index(op.f('ix_permissions__code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_connections__connection_name'), 'connections', ['connection_name'], unique=True)
    op.create_index(op.f('ix_batch_table_profiling_metrics_verify__threshold_batch_unique'), 'batch_table_profiling_metrics_verify', ['profiling_manual_threshold_id', 'batch_table_profiling_id'], unique=True)
    op.create_index(op.f('ix_batch_table_profiling_manual_thresholds__table_column_metric'), 'batch_table_profiling_manual_thresholds', ['table_id', 'column_name', 'metric_name'], unique=True)
    op.create_index(op.f('ix_batch_table_profiling__table_hour_column'), 'batch_table_profiling', ['table_id', 'processing_date_hour', 'column_name'], unique=True)
    op.create_index(op.f('ix_batch_table_metadata_metrics_verify__threshold_batch_unique'), 'batch_table_metadata_metrics_verify', ['metadata_manual_threshold_id', 'batch_table_metadata_id'], unique=True)
    op.create_index(op.f('ix_batch_table_metadata_manual_thresholds__table_metric'), 'batch_table_metadata_manual_thresholds', ['table_id', 'metric_name'], unique=True)
    op.create_index(op.f('ix_batch_table_metadata__table_hour'), 'batch_table_metadata', ['table_id', 'processing_date_hour'], unique=True)
    op.create_table('lightgbm_auc',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('table_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lightgbm_parameter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('processing_date_hour', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('auc_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('p_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('parameter_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('feature_config_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lightgbm_parameter_id'], ['lightgbm_parameters.id'], name=op.f('lightgbm_auc_lightgbm_parameter_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name=op.f('lightgbm_auc_table_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lightgbm_auc_pkey'))
    )
    op.create_index(op.f('ix_lgbm_results__table_hour_unique'), 'lightgbm_auc', ['table_id', 'processing_date_hour'], unique=True)
    op.create_index(op.f('ix_lgbm_results__table_hour'), 'lightgbm_auc', ['table_id', 'processing_date_hour'], unique=False)
    op.create_index(op.f('ix_lgbm_results__param_hour'), 'lightgbm_auc', ['lightgbm_parameter_id', 'processing_date_hour'], unique=False)
    op.create_table('lightgbm_anomaly_configs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('table_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('batch_time_col', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('required_history_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('previous_batch_hours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('history_days', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('target_sample_per_group', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('test_size', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('random_state', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('p_value_alpha', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('min_history_auc_points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exclude_cols', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('categorical_cols', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('numeric_cols', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('last_modified_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('lightgbm_anomaly_configs_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], name=op.f('lightgbm_anomaly_configs_last_modified_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name=op.f('lightgbm_anomaly_configs_table_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lightgbm_anomaly_configs_pkey'))
    )
    op.create_index(op.f('ix_lgbm_anomaly_configs__table_id'), 'lightgbm_anomaly_configs', ['table_id'], unique=True)
    op.create_table('lightgbm_auc_verify',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lightgbm_result_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('manual_threshold_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pass', 'fail', name='lightgbm_verify_status'), autoincrement=False, nullable=False),
    sa.Column('auc_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('auc_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('severity_level', postgresql.ENUM('warning', 'critical', name='manual_threshold_severity_level'), autoincrement=False, nullable=True),
    sa.Column('processing_date_hour', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_resolved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('resolved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lightgbm_result_id'], ['lightgbm_auc.id'], name=op.f('lightgbm_auc_verify_lightgbm_result_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manual_threshold_id'], ['lightgbm_auc_manual_thresholds.id'], name=op.f('lightgbm_auc_verify_manual_threshold_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('lightgbm_auc_verify_resolved_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('lightgbm_auc_verify_pkey'))
    )
    op.create_index(op.f('ix_lgbm_verify__status'), 'lightgbm_auc_verify', ['status'], unique=False)
    op.create_index(op.f('ix_lgbm_verify__result_id'), 'lightgbm_auc_verify', ['lightgbm_result_id'], unique=True)
    op.create_table('lightgbm_auc_manual_thresholds',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lightgbm_parameter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('auc_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('severity_level', postgresql.ENUM('warning', 'critical', name='manual_threshold_severity_level'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('last_modified_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('lightgbm_auc_manual_thresholds_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], name=op.f('lightgbm_auc_manual_thresholds_last_modified_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lightgbm_parameter_id'], ['lightgbm_parameters.id'], name=op.f('lightgbm_auc_manual_thresholds_lightgbm_parameter_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lightgbm_auc_manual_thresholds_pkey'))
    )
    op.create_table('lightgbm_parameters',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('table_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('learning_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('num_leaves', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_depth', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('min_data_in_leaf', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bagging_fraction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('bagging_freq', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feature_fraction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lambda_l1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lambda_l2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('min_gain_to_split', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('max_bin', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_iterations', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('last_modified_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('lightgbm_parameters_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], name=op.f('lightgbm_parameters_last_modified_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name=op.f('lightgbm_parameters_table_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lightgbm_parameters_pkey'))
    )
    op.create_index(op.f('ix_lgbm_params__table_id'), 'lightgbm_parameters', ['table_id'], unique=True)
    op.drop_index('ix_auc_verify__status', table_name='auc_verify')
    op.drop_index('ix_auc_verify__auc_result_id', table_name='auc_verify')
    op.drop_table('auc_verify')
    op.drop_index('ix_auc_results__table_hour', table_name='auc_results')
    op.drop_index('ix_auc_results__param_hour', table_name='auc_results')
    op.drop_table('auc_results')
    op.drop_table('auc_manual_thresholds')
    op.drop_index('ix_model_parameters__table_id', table_name='model_parameters')
    op.drop_table('model_parameters')
    op.drop_index('ix_model_configs__table_id', table_name='model_configs')
    op.drop_table('model_configs')
    # ### end Alembic commands ###
