"""check after rename v3

Revision ID: 61d08c3f61de
Revises: 353f75f89e8d
Create Date: 2026-05-17 16:47:53.383481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d08c3f61de'
down_revision: Union[str, Sequence[str], None] = '353f75f89e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shap_results__result_feature'), table_name='shap_results')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_shap_results__result_feature'), 'shap_results', ['auc_result_id', 'feature_name'], unique=True)
    # ### end Alembic commands ###
