"""update v1

Revision ID: 6a04da844702
Revises: 3e41ea78a027
Create Date: 2026-05-13 11:58:09.152818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a04da844702'
down_revision: Union[str, Sequence[str], None] = '3e41ea78a027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch_table_metadata_metrics_verify', sa.Column('resolved_by', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'batch_table_metadata_metrics_verify', 'users', ['resolved_by'], ['id'], ondelete='SET NULL')
    op.add_column('batch_table_profiling_metrics_verify', sa.Column('resolved_by', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'batch_table_profiling_metrics_verify', 'users', ['resolved_by'], ['id'], ondelete='SET NULL')
    op.add_column('lightgbm_auc_verify', sa.Column('resolved_by', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'lightgbm_auc_verify', 'users', ['resolved_by'], ['id'], ondelete='SET NULL')
    op.add_column('roles', sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True))
    op.create_index('ix_roles__created_by', 'roles', ['created_by'], unique=False)
    op.create_foreign_key(None, 'roles', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('rule_verify', sa.Column('resolved_by', sa.UUID(as_uuid=False), nullable=True))
    op.create_index('ix_rule_verify__is_resolved', 'rule_verify', ['is_resolved'], unique=False)
    op.create_index('ix_rule_verify__resolved_by', 'rule_verify', ['resolved_by'], unique=False)
    op.create_foreign_key(None, 'rule_verify', 'users', ['resolved_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_rules__table_is_active'), table_name='rules')
    op.drop_index(op.f('ix_rules__table_source_is_active'), table_name='rules')
    op.create_index('ix_rules__table_source_status', 'rules', ['table_id', 'source', 'is_active'], unique=False)
    op.create_index('ix_rules__table_status', 'rules', ['table_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rules__table_status', table_name='rules')
    op.drop_index('ix_rules__table_source_status', table_name='rules')
    op.create_index(op.f('ix_rules__table_source_is_active'), 'rules', ['table_id', 'source', 'is_active'], unique=False)
    op.create_index(op.f('ix_rules__table_is_active'), 'rules', ['table_id', 'is_active'], unique=False)
    op.drop_constraint(None, 'rule_verify', type_='foreignkey')
    op.drop_index('ix_rule_verify__resolved_by', table_name='rule_verify')
    op.drop_index('ix_rule_verify__is_resolved', table_name='rule_verify')
    op.drop_column('rule_verify', 'resolved_by')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_index('ix_roles__created_by', table_name='roles')
    op.drop_column('roles', 'created_by')
    op.drop_constraint(None, 'lightgbm_auc_verify', type_='foreignkey')
    op.drop_column('lightgbm_auc_verify', 'resolved_by')
    op.drop_constraint(None, 'batch_table_profiling_metrics_verify', type_='foreignkey')
    op.drop_column('batch_table_profiling_metrics_verify', 'resolved_by')
    op.drop_constraint(None, 'batch_table_metadata_metrics_verify', type_='foreignkey')
    op.drop_column('batch_table_metadata_metrics_verify', 'resolved_by')
    # ### end Alembic commands ###
