"""update anomaly threshold table

Revision ID: a7623ea11ed7
Revises: 4b0826c7ba7b
Create Date: 2026-05-13 10:19:54.106933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7623ea11ed7'
down_revision: Union[str, Sequence[str], None] = '4b0826c7ba7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lightgbm_auc_manual_thresholds', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lightgbm_auc_manual_thresholds', 'is_active')
    # ### end Alembic commands ###
