"""create latest schema v2

Revision ID: b882b0c828a1
Revises: d4a33b20eda4
Create Date: 2026-05-06 15:27:56.220734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b882b0c828a1'
down_revision: Union[str, Sequence[str], None] = 'd4a33b20eda4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch_table_metadata_metrics_verify', sa.Column('is_resolved', sa.Boolean(), nullable=False))
    op.drop_column('batch_table_metadata_metrics_verify', 'is_resolve')
    op.add_column('batch_table_profiling_metrics_verify', sa.Column('is_resolved', sa.Boolean(), nullable=False))
    op.drop_column('batch_table_profiling_metrics_verify', 'is_resolve')
    op.add_column('lightgbm_auc_verify', sa.Column('is_resolved', sa.Boolean(), nullable=False))
    op.drop_column('lightgbm_auc_verify', 'is_resolve')
    op.add_column('rule_verification_results', sa.Column('is_resolved', sa.Boolean(), nullable=False))
    op.drop_column('rule_verification_results', 'is_resolve')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule_verification_results', sa.Column('is_resolve', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('rule_verification_results', 'is_resolved')
    op.add_column('lightgbm_auc_verify', sa.Column('is_resolve', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('lightgbm_auc_verify', 'is_resolved')
    op.add_column('batch_table_profiling_metrics_verify', sa.Column('is_resolve', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('batch_table_profiling_metrics_verify', 'is_resolved')
    op.add_column('batch_table_metadata_metrics_verify', sa.Column('is_resolve', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('batch_table_metadata_metrics_verify', 'is_resolved')
    # ### end Alembic commands ###
