"""remove a field

Revision ID: c07c339c0d5c
Revises: b882b0c828a1
Create Date: 2026-05-06 19:15:09.068913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c07c339c0d5c'
down_revision: Union[str, Sequence[str], None] = 'b882b0c828a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lightgbm_auc', 'num_iterations_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lightgbm_auc', sa.Column('num_iterations_used', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
