"""Initial schema

Revision ID: c9627bbcb4ac
Revises: 
Create Date: 2026-04-26 23:52:39.797358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9627bbcb4ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('group', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('connections',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('conn_type', sa.Enum('trino', 'iceberg_rest', 'minio', name='connection_type'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_name'), 'connections', ['name'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('permission_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('table_info',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('connection_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('catalog_name', sa.String(length=255), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('layer', sa.Enum('bronze', 'silver', 'gold', name='table_layer'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('monitoring_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('batch_date_hour', sa.String(length=20), nullable=True),
    sa.Column('snapshot_id', sa.String(length=255), nullable=True),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='alert_severity'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'resolved', 'ignored', name='alert_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['table_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_table_id'), 'alerts', ['table_id'], unique=False)
    op.create_table('anomaly_detection_runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('snapshot_id', sa.String(length=255), nullable=True),
    sa.Column('batch_date_hour', sa.String(length=20), nullable=True),
    sa.Column('auc_score', sa.Float(), nullable=True),
    sa.Column('drift_status', sa.String(length=50), nullable=True),
    sa.Column('threshold_used', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['table_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_detection_runs_table_id'), 'anomaly_detection_runs', ['table_id'], unique=False)
    op.create_table('column_profile_metrics',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('snapshot_id', sa.String(length=255), nullable=False),
    sa.Column('batch_date_hour', sa.String(length=20), nullable=True),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=100), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['table_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_column_profile_metrics_snapshot_id'), 'column_profile_metrics', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_column_profile_metrics_table_id'), 'column_profile_metrics', ['table_id'], unique=False)
    op.create_table('job_runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('dag_id', sa.String(length=255), nullable=True),
    sa.Column('airflow_run_id', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', 'skipped', name='job_status'), nullable=False),
    sa.Column('batch_date_hour', sa.String(length=20), nullable=True),
    sa.Column('snapshot_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['table_info.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_runs_table_id'), 'job_runs', ['table_id'], unique=False)
    op.create_table('quality_rules',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=True),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('rule_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.Enum('system_suggested', 'manual', name='rule_source'), nullable=False),
    sa.Column('status', sa.Enum('suggested', 'enabled', 'disabled', 'rejected', name='rule_status'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='rule_severity'), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['table_info.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_rules_table_id'), 'quality_rules', ['table_id'], unique=False)
    op.create_table('quality_thresholds',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('threshold_type', sa.Enum('manual', 'auto', name='threshold_type'), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=True),
    sa.Column('upper_bound', sa.Float(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='threshold_severity'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['table_info.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_thresholds_table_id'), 'quality_thresholds', ['table_id'], unique=False)
    op.create_table('rule_validation_runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('snapshot_id', sa.String(length=255), nullable=True),
    sa.Column('batch_date_hour', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('passed', 'failed', 'warning', 'error', name='validation_status'), nullable=False),
    sa.Column('total_rules', sa.Integer(), nullable=True),
    sa.Column('passed_rules', sa.Integer(), nullable=True),
    sa.Column('failed_rules', sa.Integer(), nullable=True),
    sa.Column('warning_rules', sa.Integer(), nullable=True),
    sa.Column('anomaly_status', sa.String(length=50), nullable=True),
    sa.Column('auc_score', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['table_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_validation_runs_table_id'), 'rule_validation_runs', ['table_id'], unique=False)
    op.create_table('schema_change_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('snapshot_id', sa.String(length=255), nullable=True),
    sa.Column('change_type', sa.Enum('added', 'removed', 'type_changed', name='schema_change_type'), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('old_type', sa.String(length=100), nullable=True),
    sa.Column('new_type', sa.String(length=100), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['table_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schema_change_events_table_id'), 'schema_change_events', ['table_id'], unique=False)
    op.create_table('table_batch_metadata',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('snapshot_id', sa.String(length=255), nullable=False),
    sa.Column('parent_snapshot_id', sa.String(length=255), nullable=True),
    sa.Column('batch_date_hour', sa.String(length=20), nullable=True),
    sa.Column('committed_at', sa.DateTime(), nullable=True),
    sa.Column('operation', sa.String(length=50), nullable=True),
    sa.Column('added_records', sa.BigInteger(), nullable=True),
    sa.Column('added_files', sa.Integer(), nullable=True),
    sa.Column('added_data_files_size', sa.BigInteger(), nullable=True),
    sa.Column('total_records', sa.BigInteger(), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['table_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_batch_metadata_snapshot_id'), 'table_batch_metadata', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_table_batch_metadata_table_id'), 'table_batch_metadata', ['table_id'], unique=False)
    op.create_table('table_schema_metadata',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('snapshot_id', sa.String(length=255), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=100), nullable=True),
    sa.Column('nullable', sa.Boolean(), nullable=True),
    sa.Column('ordinal_position', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['table_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_schema_metadata_table_id'), 'table_schema_metadata', ['table_id'], unique=False)
    op.create_table('user_table_access',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('access_level', sa.Enum('view', 'manage', name='table_access_level'), nullable=False),
    sa.Column('granted_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['table_info.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomaly_feature_importance',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('shap_value', sa.Float(), nullable=True),
    sa.Column('importance_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['anomaly_detection_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_validation_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('validation_run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('rule_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('passed', 'failed', 'warning', name='result_status'), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('failed_record_count', sa.BigInteger(), nullable=True),
    sa.Column('failed_percentage', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['quality_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['validation_run_id'], ['rule_validation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_validation_results_validation_run_id'), 'rule_validation_results', ['validation_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_validation_results_validation_run_id'), table_name='rule_validation_results')
    op.drop_table('rule_validation_results')
    op.drop_table('anomaly_feature_importance')
    op.drop_table('user_table_access')
    op.drop_index(op.f('ix_table_schema_metadata_table_id'), table_name='table_schema_metadata')
    op.drop_table('table_schema_metadata')
    op.drop_index(op.f('ix_table_batch_metadata_table_id'), table_name='table_batch_metadata')
    op.drop_index(op.f('ix_table_batch_metadata_snapshot_id'), table_name='table_batch_metadata')
    op.drop_table('table_batch_metadata')
    op.drop_index(op.f('ix_schema_change_events_table_id'), table_name='schema_change_events')
    op.drop_table('schema_change_events')
    op.drop_index(op.f('ix_rule_validation_runs_table_id'), table_name='rule_validation_runs')
    op.drop_table('rule_validation_runs')
    op.drop_index(op.f('ix_quality_thresholds_table_id'), table_name='quality_thresholds')
    op.drop_table('quality_thresholds')
    op.drop_index(op.f('ix_quality_rules_table_id'), table_name='quality_rules')
    op.drop_table('quality_rules')
    op.drop_index(op.f('ix_job_runs_table_id'), table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index(op.f('ix_column_profile_metrics_table_id'), table_name='column_profile_metrics')
    op.drop_index(op.f('ix_column_profile_metrics_snapshot_id'), table_name='column_profile_metrics')
    op.drop_table('column_profile_metrics')
    op.drop_index(op.f('ix_anomaly_detection_runs_table_id'), table_name='anomaly_detection_runs')
    op.drop_table('anomaly_detection_runs')
    op.drop_index(op.f('ix_alerts_table_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('table_info')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_connections_name'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
