"""create latest schema

Revision ID: d4a33b20eda4
Revises: 
Create Date: 2026-05-06 15:26:16.987995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4a33b20eda4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('permission_group', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_permissions__code', 'permissions', ['code'], unique=True)
    op.create_index('ix_permissions__permission_group', 'permissions', ['permission_group'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_roles__is_active', 'roles', ['is_active'], unique=False)
    op.create_index('ix_roles__is_system', 'roles', ['is_system'], unique=False)
    op.create_index('ix_roles__name', 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users__email', 'users', ['email'], unique=True)
    op.create_index('ix_users__is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users__username', 'users', ['username'], unique=True)
    op.create_table('connections',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('connection_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trino_host', sa.String(length=255), nullable=False),
    sa.Column('trino_port', sa.Integer(), nullable=False),
    sa.Column('trino_user', sa.String(length=255), nullable=False),
    sa.Column('trino_password', sa.Text(), nullable=True),
    sa.Column('iceberg_rest_url', sa.String(length=255), nullable=False),
    sa.Column('iceberg_catalog_name', sa.String(length=255), nullable=False),
    sa.Column('iceberg_warehouse', sa.String(length=255), nullable=False),
    sa.Column('minio_endpoint_url', sa.String(length=255), nullable=False),
    sa.Column('minio_access_key', sa.String(length=255), nullable=False),
    sa.Column('minio_secret_key', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('last_modified_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_connections__connection_name', 'connections', ['connection_name'], unique=True)
    op.create_index('ix_connections__created_by', 'connections', ['created_by'], unique=False)
    op.create_index('ix_connections__is_active', 'connections', ['is_active'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('permission_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_index('ix_role_permissions__permission_id', 'role_permissions', ['permission_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index('ix_user_roles__role_id', 'user_roles', ['role_id'], unique=False)
    op.create_table('tables',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('connection_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('catalog_name', sa.String(length=255), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tables__connection_catalog_schema_table', 'tables', ['connection_id', 'catalog_name', 'schema_name', 'table_name'], unique=True)
    op.create_index('ix_tables__connection_id', 'tables', ['connection_id'], unique=False)
    op.create_index('ix_tables__is_active', 'tables', ['is_active'], unique=False)
    op.create_table('batch_table_metadata',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('batch_added_rows', sa.BigInteger(), nullable=True),
    sa.Column('batch_added_files', sa.Integer(), nullable=True),
    sa.Column('batch_added_files_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('table_total_rows', sa.BigInteger(), nullable=True),
    sa.Column('table_total_files', sa.Integer(), nullable=True),
    sa.Column('table_total_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('processing_date_hour', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_batch_table_metadata__processing_date_hour', 'batch_table_metadata', ['processing_date_hour'], unique=False)
    op.create_index('ix_batch_table_metadata__table_hour', 'batch_table_metadata', ['table_id', 'processing_date_hour'], unique=True)
    op.create_table('batch_table_metadata_manual_thresholds',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('min_threshold', sa.Float(), nullable=True),
    sa.Column('max_threshold', sa.Float(), nullable=True),
    sa.Column('severity_level', sa.Enum('warning', 'critical', name='manual_threshold_severity_level'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('last_modified_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_batch_table_metadata_manual_thresholds__lookup', 'batch_table_metadata_manual_thresholds', ['table_id', 'metric_name', 'is_active'], unique=False)
    op.create_index('ix_batch_table_metadata_manual_thresholds__table_active', 'batch_table_metadata_manual_thresholds', ['table_id', 'is_active'], unique=False)
    op.create_index('ix_batch_table_metadata_manual_thresholds__table_metric', 'batch_table_metadata_manual_thresholds', ['table_id', 'metric_name'], unique=True)
    op.create_table('batch_table_profiling',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=100), nullable=True),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('standard_deviation', sa.Float(), nullable=True),
    sa.Column('minimum', sa.Float(), nullable=True),
    sa.Column('maximum', sa.Float(), nullable=True),
    sa.Column('min_length', sa.Integer(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('distinctness', sa.Float(), nullable=True),
    sa.Column('approx_count_distinct', sa.BigInteger(), nullable=True),
    sa.Column('processing_date_hour', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_batch_table_profiling__processing_date_hour', 'batch_table_profiling', ['processing_date_hour'], unique=False)
    op.create_index('ix_batch_table_profiling__table_column_hour', 'batch_table_profiling', ['table_id', 'column_name', 'processing_date_hour'], unique=False)
    op.create_index('ix_batch_table_profiling__table_hour_column', 'batch_table_profiling', ['table_id', 'processing_date_hour', 'column_name'], unique=True)
    op.create_table('batch_table_profiling_manual_thresholds',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('min_threshold', sa.Float(), nullable=True),
    sa.Column('max_threshold', sa.Float(), nullable=True),
    sa.Column('severity_level', sa.Enum('warning', 'critical', name='manual_threshold_severity_level'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('last_modified_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_batch_table_profiling_manual_thresholds__lookup', 'batch_table_profiling_manual_thresholds', ['table_id', 'column_name', 'metric_name', 'is_active'], unique=False)
    op.create_index('ix_batch_table_profiling_manual_thresholds__table_active', 'batch_table_profiling_manual_thresholds', ['table_id', 'is_active'], unique=False)
    op.create_index('ix_batch_table_profiling_manual_thresholds__table_column_metric', 'batch_table_profiling_manual_thresholds', ['table_id', 'column_name', 'metric_name'], unique=True)
    op.create_table('lightgbm_parameters',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('learning_rate', sa.Float(), nullable=False),
    sa.Column('num_leaves', sa.Integer(), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('min_data_in_leaf', sa.Integer(), nullable=False),
    sa.Column('bagging_fraction', sa.Float(), nullable=False),
    sa.Column('bagging_freq', sa.Integer(), nullable=False),
    sa.Column('feature_fraction', sa.Float(), nullable=False),
    sa.Column('lambda_l1', sa.Float(), nullable=False),
    sa.Column('lambda_l2', sa.Float(), nullable=False),
    sa.Column('min_gain_to_split', sa.Float(), nullable=False),
    sa.Column('max_bin', sa.Integer(), nullable=False),
    sa.Column('num_iterations', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('last_modified_by', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lgbm_params__table_id', 'lightgbm_parameters', ['table_id'], unique=True)
    op.create_table('rules',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source', sa.Enum('system', 'manual', name='rule_source'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'inactive', name='rule_status'), nullable=False),
    sa.Column('severity_level', sa.Enum('warning', 'critical', name='manual_threshold_severity_level'), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('constraint_name', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_value', sa.String(length=255), nullable=True),
    sa.Column('suggesting_rule', sa.String(length=255), nullable=True),
    sa.Column('code_for_constraint', sa.String(length=512), nullable=False),
    sa.Column('rule_description', sa.Text(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('last_modified_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rules__table_column', 'rules', ['table_id', 'column_name'], unique=False)
    op.create_index('ix_rules__table_severity', 'rules', ['table_id', 'severity_level'], unique=False)
    op.create_index('ix_rules__table_source_column_code', 'rules', ['table_id', 'source', 'column_name', 'code_for_constraint'], unique=True)
    op.create_index('ix_rules__table_source_status', 'rules', ['table_id', 'source', 'status'], unique=False)
    op.create_index('ix_rules__table_status', 'rules', ['table_id', 'status'], unique=False)
    op.create_table('batch_table_metadata_metrics_verify',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('metadata_manual_threshold_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('batch_table_metadata_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pass', 'fail', name='metric_result_status'), nullable=False),
    sa.Column('min_threshold', sa.Float(), nullable=True),
    sa.Column('max_threshold', sa.Float(), nullable=True),
    sa.Column('severity_level', sa.Enum('warning', 'critical', name='manual_threshold_severity_level'), nullable=True),
    sa.Column('is_resolve', sa.Boolean(), nullable=False),
    sa.Column('processing_date_hour', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_table_metadata_id'], ['batch_table_metadata.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metadata_manual_threshold_id'], ['batch_table_metadata_manual_thresholds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_batch_table_metadata_metrics_verify__batch_status', 'batch_table_metadata_metrics_verify', ['batch_table_metadata_id', 'status'], unique=False)
    op.create_index('ix_batch_table_metadata_metrics_verify__threshold_batch', 'batch_table_metadata_metrics_verify', ['metadata_manual_threshold_id', 'batch_table_metadata_id'], unique=False)
    op.create_index('ix_batch_table_metadata_metrics_verify__threshold_batch_unique', 'batch_table_metadata_metrics_verify', ['metadata_manual_threshold_id', 'batch_table_metadata_id'], unique=True)
    op.create_table('batch_table_profiling_metrics_verify',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('profiling_manual_threshold_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('batch_table_profiling_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pass', 'fail', name='metric_result_status'), nullable=False),
    sa.Column('min_threshold', sa.Float(), nullable=True),
    sa.Column('max_threshold', sa.Float(), nullable=True),
    sa.Column('severity_level', sa.Enum('warning', 'critical', name='manual_threshold_severity_level'), nullable=True),
    sa.Column('is_resolve', sa.Boolean(), nullable=False),
    sa.Column('processing_date_hour', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_table_profiling_id'], ['batch_table_profiling.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profiling_manual_threshold_id'], ['batch_table_profiling_manual_thresholds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_batch_table_profiling_metrics_verify__batch_status', 'batch_table_profiling_metrics_verify', ['batch_table_profiling_id', 'status'], unique=False)
    op.create_index('ix_batch_table_profiling_metrics_verify__threshold_batch', 'batch_table_profiling_metrics_verify', ['profiling_manual_threshold_id', 'batch_table_profiling_id'], unique=False)
    op.create_index('ix_batch_table_profiling_metrics_verify__threshold_batch_unique', 'batch_table_profiling_metrics_verify', ['profiling_manual_threshold_id', 'batch_table_profiling_id'], unique=True)
    op.create_table('lightgbm_auc',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lightgbm_parameter_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('processing_date_hour', sa.DateTime(), nullable=False),
    sa.Column('auc_score', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('num_iterations_used', sa.Integer(), nullable=True),
    sa.Column('parameter_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lightgbm_parameter_id'], ['lightgbm_parameters.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lgbm_results__param_hour', 'lightgbm_auc', ['lightgbm_parameter_id', 'processing_date_hour'], unique=False)
    op.create_index('ix_lgbm_results__table_hour', 'lightgbm_auc', ['table_id', 'processing_date_hour'], unique=False)
    op.create_index('ix_lgbm_results__table_hour_unique', 'lightgbm_auc', ['table_id', 'processing_date_hour'], unique=True)
    op.create_table('lightgbm_auc_manual_thresholds',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lightgbm_parameter_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('auc_threshold', sa.Float(), nullable=False),
    sa.Column('severity_level', sa.Enum('warning', 'critical', name='manual_threshold_severity_level'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('last_modified_by', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lightgbm_parameter_id'], ['lightgbm_parameters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_verification_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('rule_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('severity_level', sa.Enum('warning', 'critical', name='manual_threshold_severity_level'), nullable=False),
    sa.Column('constraint', sa.String(length=512), nullable=True),
    sa.Column('constraint_status', sa.String(length=50), nullable=False),
    sa.Column('constraint_message', sa.Text(), nullable=True),
    sa.Column('is_resolve', sa.Boolean(), nullable=False),
    sa.Column('processing_date_hour', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rule_verification_results__rule_hour', 'rule_verification_results', ['rule_id', 'processing_date_hour'], unique=False)
    op.create_index('ix_rule_verification_results__rule_hour_unique', 'rule_verification_results', ['rule_id', 'processing_date_hour'], unique=True)
    op.create_index('ix_rule_verification_results__status_hour', 'rule_verification_results', ['constraint_status', 'processing_date_hour'], unique=False)
    op.create_table('lightgbm_auc_verify',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lightgbm_result_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('manual_threshold_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('status', sa.Enum('pass', 'fail', name='lightgbm_verify_status'), nullable=False),
    sa.Column('auc_score', sa.Float(), nullable=True),
    sa.Column('auc_threshold', sa.Float(), nullable=True),
    sa.Column('severity_level', sa.Enum('warning', 'critical', name='manual_threshold_severity_level'), nullable=True),
    sa.Column('is_resolve', sa.Boolean(), nullable=False),
    sa.Column('processing_date_hour', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lightgbm_result_id'], ['lightgbm_auc.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manual_threshold_id'], ['lightgbm_auc_manual_thresholds.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lgbm_verify__result_id', 'lightgbm_auc_verify', ['lightgbm_result_id'], unique=True)
    op.create_index('ix_lgbm_verify__status', 'lightgbm_auc_verify', ['status'], unique=False)
    op.create_table('shap_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lightgbm_result_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('feature_name', sa.String(length=255), nullable=False),
    sa.Column('shap_score', sa.Float(), nullable=False),
    sa.Column('shap_rank', sa.Integer(), nullable=False),
    sa.Column('processing_date_hour', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lightgbm_result_id'], ['lightgbm_auc.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shap_results__result_feature', 'shap_results', ['lightgbm_result_id', 'feature_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shap_results__result_feature', table_name='shap_results')
    op.drop_table('shap_results')
    op.drop_index('ix_lgbm_verify__status', table_name='lightgbm_auc_verify')
    op.drop_index('ix_lgbm_verify__result_id', table_name='lightgbm_auc_verify')
    op.drop_table('lightgbm_auc_verify')
    op.drop_index('ix_rule_verification_results__status_hour', table_name='rule_verification_results')
    op.drop_index('ix_rule_verification_results__rule_hour_unique', table_name='rule_verification_results')
    op.drop_index('ix_rule_verification_results__rule_hour', table_name='rule_verification_results')
    op.drop_table('rule_verification_results')
    op.drop_table('lightgbm_auc_manual_thresholds')
    op.drop_index('ix_lgbm_results__table_hour_unique', table_name='lightgbm_auc')
    op.drop_index('ix_lgbm_results__table_hour', table_name='lightgbm_auc')
    op.drop_index('ix_lgbm_results__param_hour', table_name='lightgbm_auc')
    op.drop_table('lightgbm_auc')
    op.drop_index('ix_batch_table_profiling_metrics_verify__threshold_batch_unique', table_name='batch_table_profiling_metrics_verify')
    op.drop_index('ix_batch_table_profiling_metrics_verify__threshold_batch', table_name='batch_table_profiling_metrics_verify')
    op.drop_index('ix_batch_table_profiling_metrics_verify__batch_status', table_name='batch_table_profiling_metrics_verify')
    op.drop_table('batch_table_profiling_metrics_verify')
    op.drop_index('ix_batch_table_metadata_metrics_verify__threshold_batch_unique', table_name='batch_table_metadata_metrics_verify')
    op.drop_index('ix_batch_table_metadata_metrics_verify__threshold_batch', table_name='batch_table_metadata_metrics_verify')
    op.drop_index('ix_batch_table_metadata_metrics_verify__batch_status', table_name='batch_table_metadata_metrics_verify')
    op.drop_table('batch_table_metadata_metrics_verify')
    op.drop_index('ix_rules__table_status', table_name='rules')
    op.drop_index('ix_rules__table_source_status', table_name='rules')
    op.drop_index('ix_rules__table_source_column_code', table_name='rules')
    op.drop_index('ix_rules__table_severity', table_name='rules')
    op.drop_index('ix_rules__table_column', table_name='rules')
    op.drop_table('rules')
    op.drop_index('ix_lgbm_params__table_id', table_name='lightgbm_parameters')
    op.drop_table('lightgbm_parameters')
    op.drop_index('ix_batch_table_profiling_manual_thresholds__table_column_metric', table_name='batch_table_profiling_manual_thresholds')
    op.drop_index('ix_batch_table_profiling_manual_thresholds__table_active', table_name='batch_table_profiling_manual_thresholds')
    op.drop_index('ix_batch_table_profiling_manual_thresholds__lookup', table_name='batch_table_profiling_manual_thresholds')
    op.drop_table('batch_table_profiling_manual_thresholds')
    op.drop_index('ix_batch_table_profiling__table_hour_column', table_name='batch_table_profiling')
    op.drop_index('ix_batch_table_profiling__table_column_hour', table_name='batch_table_profiling')
    op.drop_index('ix_batch_table_profiling__processing_date_hour', table_name='batch_table_profiling')
    op.drop_table('batch_table_profiling')
    op.drop_index('ix_batch_table_metadata_manual_thresholds__table_metric', table_name='batch_table_metadata_manual_thresholds')
    op.drop_index('ix_batch_table_metadata_manual_thresholds__table_active', table_name='batch_table_metadata_manual_thresholds')
    op.drop_index('ix_batch_table_metadata_manual_thresholds__lookup', table_name='batch_table_metadata_manual_thresholds')
    op.drop_table('batch_table_metadata_manual_thresholds')
    op.drop_index('ix_batch_table_metadata__table_hour', table_name='batch_table_metadata')
    op.drop_index('ix_batch_table_metadata__processing_date_hour', table_name='batch_table_metadata')
    op.drop_table('batch_table_metadata')
    op.drop_index('ix_tables__is_active', table_name='tables')
    op.drop_index('ix_tables__connection_id', table_name='tables')
    op.drop_index('ix_tables__connection_catalog_schema_table', table_name='tables')
    op.drop_table('tables')
    op.drop_index('ix_user_roles__role_id', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('ix_role_permissions__permission_id', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('ix_connections__is_active', table_name='connections')
    op.drop_index('ix_connections__created_by', table_name='connections')
    op.drop_index('ix_connections__connection_name', table_name='connections')
    op.drop_table('connections')
    op.drop_index('ix_users__username', table_name='users')
    op.drop_index('ix_users__is_active', table_name='users')
    op.drop_index('ix_users__email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_roles__name', table_name='roles')
    op.drop_index('ix_roles__is_system', table_name='roles')
    op.drop_index('ix_roles__is_active', table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_permissions__permission_group', table_name='permissions')
    op.drop_index('ix_permissions__code', table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
