apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: PostgreSQL
    type: postgres
    access: proxy
    editable: true
    isDefault: true
    version: 2
    url: datagate_database:5432
    user: admin
    secureJsonData:
      password: datagatepassword
    jsonData:
      database: datagate
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
