name: datagate
services:
  trino:
    image: 'trinodb/trino:479'
    hostname: trino
    container_name: datagate_trino
    ports:
      - '8085:8080'
    volumes:
      - ./etc:/etc/trino
    environment:
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - datagate_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/info"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  datagate_net:
    external: true